version: '3.7'

services:

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    volumes:
      - './services/backend:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=app.main.DevelopmentConfig
      - DATABASE_URL=mysql+pymysql://online_games:Flask#123@localhost:8181/online_games_db?charset=utf8mb4
      - DATABASE_TEST_mysql+pymysql://online_games:Flask#123@localhost:8181/online_games_db?charset=utf8mb4
      - SECRET_KEY=my_precious_secret_key
      - ADMIN_SECRET_KEY=admin_precious_secret_key
    depends_on:
      - database
      - redis

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Flask#123
      MYSQL_USER: online_games
      MYSQL_PASSWORD: Flask#123
      MYSQL_DATABASE: online_games_db
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - ./conf/mariadb-conf.d:/etc/mysql/mariadb.conf.d
      - ./conf/conf.d:/etc/mysql/conf.d/
    ports:
      - "8181:3306"

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
    ports:
      - 5436:5432

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_SERVICE_URL=${REACT_APP_BACKEND_SERVICE_URL}
    depends_on:
      - backend

  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile
    volumes:
        - './services/swagger/swagger.json:/usr/share/nginx/html/swagger.json'
    ports:
      - 3008:8080
    environment:
      - URL=swagger.json
    depends_on:
      - backend

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8085:80
    depends_on:
      - backend
      - client


networks:
  redis-net:

volumes:
  redis-data: