version: '3.7'

services:

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Flask#123
      MYSQL_USER: online_games
      MYSQL_PASSWORD: Flask#123
      MYSQL_DATABASE: online_games_db
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - ./conf/mariadb-conf.d:/etc/mysql/mariadb.conf.d
      - ./conf/conf.d:/etc/mysql/conf.d/
    ports:
      - "8181:3306"

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
    ports:
      - 5436:5432

networks:
  redis-net:

volumes:
  redis-data: