# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: online_games
      MYSQL_PASSWORD: Flask#123
      MYSQL_DATABASE: online_games_db
    ports:
      - "8181:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8182:8080

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
    ports:
      - 8183:6379

networks:
  redis-net:

volumes:
  redis-data:


